#cluster_slurm.yaml for subtract_mouse_and_realign.snakefile
#Anna-Lisa Doebley
#Template made 2021-09-24
#Ha Lab
#Fred Hutchinson Cancer Research Center

__default__:
    partition: campus-new
    time: "24:0:0"
    mem: 4G
    ncpus: 1
    ntasks: 1
    output: logs/cluster/{rule}.{wildcards.samples}.%A.out
    JobName: "{rule}.{wildcards.samples}.%A"

unmap:
    partition: campus-new
    mem: 72G
    ncpus: 6
    time: "72:0:0"

map_to_ConcatRef:
    time: "48:0:0"
    mem: 12G
    ncpus: 4

sort_concatRef_by_coord:
    mem: 8G

###
unmap_human_cleaned:
    partition: campus-new
    mem: 72G
    ncpus: 6
    time: "72:0:0"

unmap_mouse_cleaned:
    partition: campus-new
    mem: 72G
    ncpus: 6
    time: "72:0:0"

map_to_human_ref:
    time: "48:0:0"
    mem: 12G
    ncpus: 4

map_to_mouse_ref:
    time: "48:0:0"
    mem: 12G
    ncpus: 4

mark_dups_cleaned_human:
    partition: campus-new
    mem: 72G
    ncpus: 6

mark_dups_cleaned_mouse:
    partition: campus-new
    mem: 72G
    ncpus: 6
