#config.yaml for subtract_mouse_and_realign.snakefile
#Anna-Lisa Doebley
#Template made 2021-09-24
#Ha Lab
#Fred Hutchinson Cancer Research Center

#SELECT CORRECT REFERENCE GENOME
#if the input is a cram file, specify the reference gnenome
input_reference_genome: 'null'
#/shared/biodata/ngs/Reference/iGenomes/Homo_sapiens/UCSC/hg38/Sequence/BWAIndex/genome.fa
#input_reference_genome: 'null' #for bam file input

#location of the concatref genome for mouse subtraction
ConcatRef_genome: /fh/fast/henikoff_s/user/jgreene/refs/hg38_plus_mm10_BWA/GRCh38_plus_UCSC_mm10.fa #ConcatRef created by concatenate_reference.py
    #/path/to/GRCh38_plus_NCBI_GRCm38.fa #option used by Anna-Lisa in her projects

#reference genome for realignment, with index files in same folder as .fa file
human_reference_genome: /shared/biodata/ngs/Reference/iGenomes/Homo_sapiens/UCSC/hg38/Sequence/BWAIndex/genome.fa #human reference genome
    #/path/to/GRCh38.fa #option used by Anna-Lisa in her projects

#reference genome for realignment, with index files in same folder as .fa file
bowtie2_human_reference_genome: /shared/biodata/ngs/Reference/iGenomes/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index/genome #human reference genome
    #/path/to/GRCh38.fa #option used by Anna-Lisa in her projects

#reference genome for realignment, with index files in same folder as .fa file
mouse_reference_genome: /shared/biodata/ngs/Reference/iGenomes/Mus_musculus/UCSC/mm10/Sequence/BWAIndex/genome.fa #mouse reference genome
    #/path/to/mm10.fa #option used by Anna-Lisa in her projects

#reference genome for realignment, with index files in same folder as .fa file
bowtie2_mouse_reference_genome: /shared/biodata/ngs/Reference/iGenomes/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome #mouse reference genome
    #/path/to/mm10.fa #option used by Anna-Lisa in her projects


tag: UCSC_mm10  #make sure to use the same tag info of ConcatRef
    #NCBI_GRCm38 #option used by Anna-Lisa in her projects

human_tag: UCSC_hg38  #make sure to use the same tag info of ConcatRef
    #NCBI_GRCm38 #option used by Anna-Lisa in her projects

#specify a path for the logs and results
results_path: /fh/fast/henikoff_s/user/jgreene/projects/sciCnT/data/DJ_Hs_BY_K27me3_KHRM3_220802/bams_ALL/concat-ref_OUT_final

#SELECT CORRECT POLYMORPHIC SITES
known_polymorphic_sites1: /path/to/dbsnp_151_hg38_with_chr.All_20180418.vcf.gz

known_polymorphic_sites2: /path/to/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz

#SELECT IF DATA IS WHOLE GENOME SEQUENCES OR NOT (True or False)
#determines if rule get_wgs_metrics is run
is_wgs: True

#SELECT CORRECT BASE RECALIBRATOR GAP OPEN PENALTY
#GATK recommends 40 for exomes and 30 for whole genomes
base_recalibrator_gap_open_penalty: 30.0

#can adjust the number of threads used for bwa based on the data
#suggested this matches cluster_slurm.yaml ncpus for map_to_reference rule
bwa_threads: 16

#tools used.  need to be module loaded first.  see snakemake file for loads
bwa: /app/software/BWA/0.7.17-foss-2018b/bin/bwa
bowtie2: /home/jgreene3/.conda/envs/2for1/bin/bowtie2
samtools: /app/software/SAMtools/1.16.1-GCC-11.2.0/bin/samtools
gatk: /app/software/GATK/4.1.4.1-GCCcore-8.3.0-Java-11/gatk
picard: /home/jgreene3/.conda/envs/2for1/bin/picard
