samples:
  40cpw: /shared/ngs/illumina/henikoff/220817_bowtie2/single_cell/DJ_Hs/hg38/sams/DJ_Hs_BY_K27me3_KHRM3_40cpw_220802.sam
  20cpw: /shared/ngs/illumina/henikoff/220817_bowtie2/single_cell/DJ_Hs/hg38/sams/DJ_Hs_BY_K27me3_KHRM3_20cpw_220802.sam
  10cpw: /shared/ngs/illumina/henikoff/220817_bowtie2/single_cell/DJ_Hs/hg38/sams/DJ_Hs_BY_K27me3_KHRM3_10cpw_220802.sam
  5cpw: /shared/ngs/illumina/henikoff/220817_bowtie2/single_cell/DJ_Hs/hg38/sams/DJ_Hs_BY_K27me3_KHRM3_5cpw_220802.sam